19-Aug-2025 13:36:18.839 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:28)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
	Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
		at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		... 30 more
	Caused by: java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		... 33 more
19-Aug-2025 13:36:18.840 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:28)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 13:40:36.238 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:28)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
	Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
		at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		... 30 more
	Caused by: java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		... 33 more
19-Aug-2025 13:40:36.239 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:28)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 13:45:53.063 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:28)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
	Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
		at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		... 30 more
	Caused by: java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		... 33 more
19-Aug-2025 13:45:53.063 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:28)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 14:21:06.341 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
	Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
		at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		... 30 more
	Caused by: java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		... 33 more
19-Aug-2025 14:21:06.342 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 14:30:05.758 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
	Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
		at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		... 30 more
	Caused by: java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		... 33 more
19-Aug-2025 14:30:05.759 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 14:59:05.551 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
19-Aug-2025 14:59:05.551 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 15:26:09.107 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
19-Aug-2025 15:26:09.107 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 15:38:08.297 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
19-Aug-2025 15:38:08.297 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 15:41:28.931 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
19-Aug-2025 15:41:28.935 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.sql.SQLSyntaxErrorException: Unknown database 'billing'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
19-Aug-2025 20:34:02.001 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [controller.ItemController] threw exception
	java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at controller.ItemController.init(ItemController.java:26)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
	Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		... 22 more
	Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
		at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		... 30 more
	Caused by: java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		... 33 more
19-Aug-2025 20:34:02.005 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [controller.ItemController]
	java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:579)
		at java.base/sun.nio.ch.Net.connect(Net.java:568)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:633)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
		at util.DBConnection.getConnection(DBConnection.java:29)
		at dao.ItemDAO.<init>(ItemDAO.java:16)
		at controller.ItemController.init(ItemController.java:24)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:842)
